name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (Ruby ${{ matrix.ruby }})
    strategy:
      matrix:
        ruby:
          - ruby-head
          - jruby
          - truffleruby
          - ruby

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test

  lint:
    runs-on: ubuntu-latest
    name: Standard Ruby
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Standard Ruby
        run: bundle exec rake standard
      - name: RBS validate
        run: bundle exec rake rbs:validate
